### PR TITLE
feat: add keymaps for actions

### PR DESCRIPTION
**Pull request by arnevm123**
While using the plugin I found some documentation missing, please let me know if something is not accurate

### CODE REVIEW

**Comment by arnevm123** [comment]
Not sure if  I think peek is implemented as "Checkpoint", as this seems to be a similar purpose?
Also if you think the added keymaps are not "Actions" I can put these in another table.
If you think any descriptions are wrong/ you have some suggestions I can change them.
Or feel free to edit them yourself if you find that easier :smile:

**Comment by AdeAttwood** [comment]
Yea this looks good, you are correct about the checkpoint and peek this is inconsistent naming. I think we will park this until https://github.com/AdeAttwood/ivy.nvim/pull/81 is done. I would really love to use the `ftplugin/ivy.lua` pattern, however I don't think it will work amazing with the external plugin managers we have now. 

I think I am just going to have to accept that there are not many of us still using vim packages.

**Comment by AdeAttwood** [comment]
@arnevm123 after some thought, I am going to get this in and remove "Pending" from the code base to try and make things more consistent.

I also think there is a conversation to be had around this table of actions, they way the actions are defined right now are a little too specific to file finding or another action you are going to a point in a file. I may try to find some time to make this more generic and align the language with the original emacs package.

Thanks again for all the suggestions and contributions :heart:

**Comment by arnevm123** [comment]
No worries, thank you for this amazing plugin and listening to my suggestions!

When I first saw the plugin I thought it was already really big, as it looks amazing and works like a charm!

**Pull request merged**
